/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telasAdm;

import java.awt.Color;
import java.awt.Cursor;
import telas.Metodos;


/**
 *
 * @author Pichau
 */
public class AddDoce extends javax.swing.JFrame {

    /**
     * Creates new form Painel
     */
    public AddDoce() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Voltar = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        txtNomeDoce = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        Sair = new javax.swing.JLabel();
        btnSelecionarFoto = new javax.swing.JButton();
        btnAddDoce = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(175, 176, 232));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(225, 34, 127)));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADICIONAR DOCE");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/logoamandita2.png"))); // NOI18N

        Voltar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Voltar.setForeground(new java.awt.Color(255, 255, 255));
        Voltar.setText("VOLTAR");
        Voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VoltarMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/SetaLeft.png"))); // NOI18N

        txtDescricao.setBackground(new java.awt.Color(175, 176, 232));
        txtDescricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDescricao.setForeground(new java.awt.Color(255, 255, 255));
        txtDescricao.setText("DESCRIÇÃO:");
        txtDescricao.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtDescricao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDescricaoMouseClicked(evt);
            }
        });
        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });

        txtNomeDoce.setBackground(new java.awt.Color(175, 176, 232));
        txtNomeDoce.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNomeDoce.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeDoce.setText("NOME DO DOCE:");
        txtNomeDoce.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtNomeDoce.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNomeDoceMouseClicked(evt);
            }
        });
        txtNomeDoce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeDoceActionPerformed(evt);
            }
        });

        txtPreco.setBackground(new java.awt.Color(175, 176, 232));
        txtPreco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPreco.setForeground(new java.awt.Color(255, 255, 255));
        txtPreco.setText("PREÇO:");
        txtPreco.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtPreco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPrecoMouseClicked(evt);
            }
        });
        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });

        Sair.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        Sair.setForeground(new java.awt.Color(255, 255, 255));
        Sair.setText("X");
        Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SairMouseExited(evt);
            }
        });

        btnSelecionarFoto.setBackground(new java.awt.Color(220, 27, 116));
        btnSelecionarFoto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSelecionarFoto.setForeground(new java.awt.Color(255, 255, 255));
        btnSelecionarFoto.setText("SELECIONAR FOTO");
        btnSelecionarFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSelecionarFotoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSelecionarFotoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSelecionarFotoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSelecionarFotoMouseReleased(evt);
            }
        });
        btnSelecionarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarFotoActionPerformed(evt);
            }
        });

        btnAddDoce.setBackground(new java.awt.Color(220, 27, 116));
        btnAddDoce.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddDoce.setForeground(new java.awt.Color(255, 255, 255));
        btnAddDoce.setText("ADICIONAR DOCE");
        btnAddDoce.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddDoceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddDoceMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAddDoceMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAddDoceMouseReleased(evt);
            }
        });
        btnAddDoce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDoceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Voltar)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 47, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeDoce, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(btnAddDoce, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(btnSelecionarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Voltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(txtNomeDoce, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnSelecionarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddDoce, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseClicked
        new Painel().setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarMouseClicked

    private void VoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseEntered
        Voltar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        Voltar.setForeground(new Color(220,27,116));
    }//GEN-LAST:event_VoltarMouseEntered

    private void VoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseExited
        Voltar.setForeground(Color.white);
    }//GEN-LAST:event_VoltarMouseExited

    private void txtDescricaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDescricaoMouseClicked
        txtDescricao.setText("");
    }//GEN-LAST:event_txtDescricaoMouseClicked

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void txtNomeDoceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomeDoceMouseClicked
        txtNomeDoce.setText("");
    }//GEN-LAST:event_txtNomeDoceMouseClicked

    private void txtNomeDoceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeDoceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeDoceActionPerformed

    private void txtPrecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrecoMouseClicked
        txtPreco.setText("");
    }//GEN-LAST:event_txtPrecoMouseClicked

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseClicked
        //quando clicar
        System.exit(0);
    }//GEN-LAST:event_SairMouseClicked

    private void SairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseEntered
        Metodos.Labelentered(Sair);
    }//GEN-LAST:event_SairMouseEntered

    private void SairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseExited
        Metodos.Labeexit(Sair);
    }//GEN-LAST:event_SairMouseExited

    private void btnSelecionarFotoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelecionarFotoMouseEntered
        Metodos.btnentered(btnSelecionarFoto);
    }//GEN-LAST:event_btnSelecionarFotoMouseEntered

    private void btnSelecionarFotoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelecionarFotoMouseExited
        Metodos.btnexit(btnSelecionarFoto);
    }//GEN-LAST:event_btnSelecionarFotoMouseExited

    private void btnSelecionarFotoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelecionarFotoMousePressed
        Metodos.btnpress(btnSelecionarFoto);
    }//GEN-LAST:event_btnSelecionarFotoMousePressed

    private void btnSelecionarFotoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelecionarFotoMouseReleased
        Metodos.btnexit(btnSelecionarFoto);
    }//GEN-LAST:event_btnSelecionarFotoMouseReleased

    private void btnAddDoceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddDoceMouseEntered
        Metodos.btnentered(btnAddDoce);
    }//GEN-LAST:event_btnAddDoceMouseEntered

    private void btnAddDoceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddDoceMouseExited
        Metodos.btnexit(btnAddDoce);
    }//GEN-LAST:event_btnAddDoceMouseExited

    private void btnAddDoceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddDoceMousePressed
        Metodos.btnpress(btnAddDoce);
    }//GEN-LAST:event_btnAddDoceMousePressed

    private void btnAddDoceMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddDoceMouseReleased
        Metodos.btnexit(btnAddDoce);
    }//GEN-LAST:event_btnAddDoceMouseReleased

    private void btnAddDoceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDoceActionPerformed
        
        
        
        // Botão para adicionar o doce
        
        
    }//GEN-LAST:event_btnAddDoceActionPerformed

    private void btnSelecionarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarFotoActionPerformed
        
        
        
        // Botão selecionar foto
        
        
    }//GEN-LAST:event_btnSelecionarFotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDoce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDoce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDoce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDoce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDoce().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Sair;
    private javax.swing.JLabel Voltar;
    private javax.swing.JButton btnAddDoce;
    private javax.swing.JButton btnSelecionarFoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtNomeDoce;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
