/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Pichau
 */

import java.awt.Color;
import java.awt.Cursor;

public class Cardapio extends javax.swing.JFrame {

    /**
     * Creates new form Cardapio
     */
    int index;
    public Cardapio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaTeste = new javax.swing.JList<>();
        Proxima1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Sair = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Minhaconta1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Minhaconta3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(175, 176, 232));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(225, 34, 127)));

        listaTeste.setBackground(new java.awt.Color(175, 176, 232));
        listaTeste.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 0, 4, new java.awt.Color(225, 34, 127)));
        listaTeste.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        listaTeste.setForeground(new java.awt.Color(255, 255, 255));
        listaTeste.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "⸻⸻⸻⸻⸻⸻", " ", "           CHOCOLATE", " ", "⸻⸻⸻⸻⸻⸻", " ", "                NINHO", " ", "⸻⸻⸻⸻⸻⸻", " ", "               NUTELA", " ", "⸻⸻⸻⸻⸻⸻", " ", "             MORANGO", " ", "⸻⸻⸻⸻⸻⸻", " ", "         DOCE DE LEITE", " ", "⸻⸻⸻⸻⸻⸻" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaTeste.setSelectionBackground(new java.awt.Color(175, 176, 232));
        listaTeste.setSelectionForeground(new java.awt.Color(225, 34, 127));
        listaTeste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaTesteMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(listaTeste);

        Proxima1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Proxima1.setForeground(new java.awt.Color(255, 255, 255));
        Proxima1.setText("PRÓXIMA");
        Proxima1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Proxima1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Proxima1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Proxima1MouseExited(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/setaRight.png"))); // NOI18N

        Sair.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        Sair.setForeground(new java.awt.Color(255, 255, 255));
        Sair.setText("X");
        Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SairMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 50)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CARDÁPIO");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("DOCES SOB ENCOMENDA");

        Minhaconta1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Minhaconta1.setForeground(new java.awt.Color(255, 255, 255));
        Minhaconta1.setText("CARRINHO");
        Minhaconta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Minhaconta1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Minhaconta1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Minhaconta1MouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/logoamandita2.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/usuario.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Carrinho.png"))); // NOI18N

        Minhaconta3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Minhaconta3.setForeground(new java.awt.Color(255, 255, 255));
        Minhaconta3.setText("MINHA CONTA");
        Minhaconta3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Minhaconta3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Minhaconta3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Minhaconta3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(260, 260, 260))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(Proxima1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Minhaconta3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Minhaconta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 29, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Minhaconta3)
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Minhaconta1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))))
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Proxima1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void listaTesteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaTesteMouseClicked

        TelaChocolate choco = new TelaChocolate();
        TelaDocedeLeite doceleite = new TelaDocedeLeite();
        TelaMorango morango = new TelaMorango();
        TelaNinho ninho = new TelaNinho();
        TelaNutela nutela = new TelaNutela();

        //pegar essa variável index entender onde eu clico do JList
        index = listaTeste.getSelectedIndex();

        int opcao = listaTeste.getSelectedIndex();

        switch (opcao) {

            case 2:

            //os disposes não estão funcionando
            ninho.dispose();
            doceleite.dispose();
            morango.dispose();
            nutela.dispose();
            choco.setVisible(true);
            break;

            case 6:
            doceleite.dispose();
            morango.dispose();
            nutela.dispose();
            choco.dispose();
            ninho.setVisible(true);
            break;

            case 10:
            ninho.dispose();
            doceleite.dispose();
            morango.dispose();
            choco.dispose();
            nutela.setVisible(true);
            break;

            case 14:
            ninho.dispose();
            doceleite.dispose();
            nutela.dispose();
            choco.dispose();
            morango.setVisible(true);
            break;

            case 18:
            ninho.dispose();
            morango.dispose();
            nutela.dispose();
            choco.dispose();
            doceleite.setVisible(true);
            break;

        }
    }//GEN-LAST:event_listaTesteMouseClicked

    private void Proxima1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Proxima1MouseClicked
        new Carrinho().setVisible(true);
        dispose();
    }//GEN-LAST:event_Proxima1MouseClicked

    private void Proxima1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Proxima1MouseEntered
        Proxima1.setCursor(new Cursor(Cursor.HAND_CURSOR));
        Proxima1.setForeground(new Color(220,27,116));
    }//GEN-LAST:event_Proxima1MouseEntered

    private void Proxima1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Proxima1MouseExited
        Proxima1.setForeground(Color.white);
    }//GEN-LAST:event_Proxima1MouseExited

    private void SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseClicked
        //quando clicar
        System.exit(0);
    }//GEN-LAST:event_SairMouseClicked

    private void SairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseEntered
        Metodos.Labelentered(Sair);
    }//GEN-LAST:event_SairMouseEntered

    private void SairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseExited
        Metodos.Labeexit(Sair);
    }//GEN-LAST:event_SairMouseExited

    private void Minhaconta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minhaconta1MouseClicked
        new Carrinho().setVisible(true);
        dispose();
    }//GEN-LAST:event_Minhaconta1MouseClicked

    private void Minhaconta1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minhaconta1MouseEntered
        Minhaconta1.setCursor(new Cursor(Cursor.HAND_CURSOR));
        Minhaconta1.setForeground(new Color(220,27,116));
    }//GEN-LAST:event_Minhaconta1MouseEntered

    private void Minhaconta1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minhaconta1MouseExited
        Minhaconta1.setForeground(Color.white);
    }//GEN-LAST:event_Minhaconta1MouseExited

    private void Minhaconta3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minhaconta3MouseClicked
        new Perfil().setVisible(true);
        dispose();
    }//GEN-LAST:event_Minhaconta3MouseClicked

    private void Minhaconta3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minhaconta3MouseEntered
        Minhaconta3.setCursor(new Cursor(Cursor.HAND_CURSOR));
        Minhaconta3.setForeground(new Color(220,27,116));
    }//GEN-LAST:event_Minhaconta3MouseEntered

    private void Minhaconta3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minhaconta3MouseExited
        Minhaconta3.setForeground(Color.white);
    }//GEN-LAST:event_Minhaconta3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cardapio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Minhaconta1;
    private javax.swing.JLabel Minhaconta3;
    private javax.swing.JLabel Proxima1;
    private javax.swing.JLabel Sair;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> listaTeste;
    // End of variables declaration//GEN-END:variables
}
